name: Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        nox-session: ["tests"]
      include:
        - os: macos-latest
          python-version: "3.10"
          nox-session: "tests"
        - os: ubuntu-latest
          python-version: "3.10"
          nox-session: "lint"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: python -m pip install -U nox
      - name: Run tests
        run: python -m nox --non-interactive -s ${{ matrix.nox-session }}

  release:
    needs: tests
    uses: dfm/workflows/.github/workflows/python-release.yml@main
      with:
        wheels: true
      secrets:
        pypi-token: ${{ secrets.pypi_token }}
